ignore:
  - "examples/"
  - "tests/"

# append_unmatched: true 

nav:
  - Inicio: index.md
  - User Guide:
      - Introducci贸n: user/setup.md
      - Interfaz: 
        - Paneles: user/interface/panels.md
        - Toolbars: user/interface/toolbars.md
      - Workflow: user/workflow.md
  - Dev Guide:
    - Introducci贸n: dev/home.md
    - publisher: 
      - Introducci贸n: dev/publisher/readme.md
      - Examples: dev/publisher/examples.md
      - Modules: dev/publisher/modules.md
      - api:
        - dev/publisher/*.md
        - dev/publisher/*
    - plugins: 
      - Introducci贸n: dev/task_schema/readme.md
      - Examples: dev/task_schema/examples.md
      - Modules: dev/task_schema/modules.md
      - api:
        - dev/task_schema/*.md
        - dev/task_schema/*