FROM python:3.10.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

COPY . .
EXPOSE 8001

# CMD ["uvicorn", "main:app", "--host", "localhost", "--port", "8001"]
CMD ["fastapi", "run", "main.py", "--port", "8001"]
