site_name: Wiki GwaIO
nav:
  - Inicio: index.md
  - User Guide: 
      - Introducción: user/setup.md
      - Interfaz: 
        - Paneles: user/interface/panels.md
        - Toolbars: user/interface/toolbars.md
      - Workflow: user/workflow.md
  - Dev Guide:
    - Introducción: dev/home.md
theme:
  name: material
  custom_dir: overrides
  icon: 
    logo: gwaio-icon
  favicon: resources/img/gwaio-favicon.ico
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Tema claro
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Tema oscuro
      media: "(prefers-color-scheme: dark)"
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant.preview
    - navigation.indexes
    - navigation.tracking
    - navigation.footer
    - navigation.top
    - search.suggest
    - search.highlight
markdown_extensions:
  - admonition
  - pymdownx.blocks.caption
  - attr_list
  - md_in_html

extra_css:
  - css/chat.css
  - css/extra.css
  - css/gwaio.css
extra_javascript:
  - js/chat.js
plugins:
  - search
  - glightbox
  - mkdocs-video:
      is_video: True
      video_autoplay: False
  - mkdocs-vtranscript
  - mkdocstrings